create table patient(
                        id int generated by default as identity primary key ,
                        uuid uuid not null unique ,
                        full_name varchar(100) not null unique,
                        date_of_birth date not null
);
create table doctor(
                       id int generated by default as identity primary key ,
                       uuid uuid not null  unique ,
                       full_name varchar(100) not null unique
);
create table ticket(
                       id int generated by default as identity primary key ,
                       patient_uuid uuid references patient(uuid) on delete cascade ,
                       doctor_uuid uuid references doctor(uuid) on delete cascade ,
                       date timestamp
);